### ISSUE TITLE
execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by AparnaManjalavil** [mesibo/messenger-app-android-kotlin#4]
This compilation problem had never occurred before, but it popped up today.
 Build error is shown below :-
app\build\intermediates\packaged_manifests\debug\AndroidManifest.xml:247: AAPT: error: attribute android:foregroundServiceType not found.
 I am tried to clone the project again but it show the same error. Then I attempted to do invalidate caches and restart but it failed.
Lastly tried to run after delete intermediate folder under app/build.
I am using new call api-1.2.26.

**Comment by mesibo** [comment]
what is your compile SDK version?

**Comment by AparnaManjalavil** [comment]
compile SDK version 28

**Comment by mesibo** [comment]
Update it to 29 

Also perform, File-> Sync Project with Gradle files

**Comment by AparnaManjalavil** [comment]
Thank you
