### ISSUE TITLE
Message and calls are can't send

### ISSUE THREAD

**Issue by AparnaExalture** [mesibo/messenger-app-android-kotlin#6]
I am trying to clone this repository and an issue founded that message and calls are not received if sender and receiver are on different network. How to solve this ?.
Call Api -1.2.26
Compile sdk version - 29
Sender send me a message at 15:20
![IMG-20210111-WA0007](https://user-images.githubusercontent.com/75716846/104167984-4ef1f380-5423-11eb-83d6-dee25c3d874a.jpg)
But I have received not yet.
![Screenshot_2021-01-11-15-31-36-26_19892202b96a733f44fe0181fae7d9e4](https://user-images.githubusercontent.com/75716846/104168113-82cd1900-5423-11eb-93bc-0c3e32386d05.jpg)

**Comment by mesibo** [comment]
Furthe
